#!/bin/bash

THEME=$1

if [ -z ${THEME+x} ]; then
	echo "Usage: link-waybar-theme [cute|evil|vim]"
else
	ln -sf ~/.config/waybar/$THEME.jsonc ~/.config/waybar/config.jsonc
	ln -sf ~/.config/waybar/$THEME.css ~/.config/waybar/style.css
fi
