alias grep="rg $@"
alias find="fd $@"
alias df="duf $@"
alias ls="exa --git --icons $@"
alias l="ls -a -l $@"
alias cat="bat $@"
alias dig="dog $@"
alias sudo="doas $@"

alias g="git $@"
alias gaa="git add --all $@"
alias gca="git commit --all $@"
alias gd="git diff $@"
alias gi="git init $@"
alias gs="git status --short $@"
alias gsa="git status $@"
alias gp="git push $@"
alias gpl="git pull $@"

alias pp="pnpm $@"
alias ppi="pnpm install $@"
alias ppii="pnpm init $@"
alias ppu="pnpm update $@"
alias ppui="pnpm uninstall $@"
alias ppd="pnpm dev $@"
alias ppl="pnpm lint $@"
alias ppf="pnpm format $@"
